title: "Open Evidence"
author: "Christopher Steven Marcum, Ph.D., F.G.S.A."
description: "Perspectives on science, data, and technology that don't fit anywhere else."
url: "http://www.chrismacum.com" 
baseurl: "/marcum-blog"

plugins:
  - jekyll-feed

feed:
  path: /feed.xml
